import VinForm from "./components/VinForm"
import Attribution from "./components/Attribution"
import { useState } from "react"
import CarDetails from "./components/CarDetails"

export interface CarDetailsInterface {
    "Active Safety System Note": string,
    "Adaptive Cruise Control (ACC)": string,
    "Adaptive Driving Beam (ADB)": string,
    "Additional Error Text": string,
    "Anti-lock Braking System (ABS)": string,
    "Auto-Reverse System for Windows and Sunroofs": string, 
    "Automatic Crash Notification (ACN) / Advanced Automatic Crash Notification (AACN)": string,
    "Automatic Pedestrian Alerting Sound (for Hybrid and EV only)": string,
    "Axle Configuration": string,
    "Axles": string,
    "Backup Camera": string,
    "Base Price ($)": string,
    "Battery Current (Amps) From": string,
    "Battery Current (Amps) To": string,
    "Battery Energy (kWh) From": string,
    "Battery Energy (kWh) To": string,
    "Battery Type": string,
    "Battery Voltage (Volts) From": string,
    "Battery Voltage (Volts) To": string,
    "Bed Length (inches)": string,
    "Bed Type": string,
    "Blind Spot Intervention (BSI)": string,
    "Blind Spot Warning (BSW)": string,
    "Body Class": string,
    "Brake System Description": string,
    "Brake System Type": string,
    "Bus Floor Configuration Type": string,
    "Bus Length (feet)": string,
    "Bus Type": string,
    "Cab Type": string,
    "Charger Level": string,
    "Charger Power (kW)": string,
    "Combined Braking System (CBS)": string,
    "Cooling Type": string,
    "Crash Imminent Braking (CIB)": string,
    "Curb Weight (pounds)": string,
    "Curtain Air Bag Locations": string,
    "Custom Motorcycle Type": string,
    "Daytime Running Light (DRL)": string,
    "Destination Market": string,
    "Displacement (CC)": string,
    "Displacement (CI)": string,
    "Displacement (L)": string,
    "Doors": string,
    "Drive Type": string,
    "Dynamic Brake Support (DBS)": string,
    "EV Drive Unit": string,
    "Electrification Level": string,
    "Electronic Stability Control (ESC)": string,
    "Engine Brake (hp) From": string,
    "Engine Brake (hp) To": string,
    "Engine Configuration": string,
    "Engine Manufacturer": string,
    "Engine Model": string,
    "Engine Number of Cylinders": string,
    "Engine Power (kW)": string,
    "Engine Stroke Cycles": string,
    "Entertainment System": string,
    "Error Code": string,
    "Error Text": string,
    "Event Data Recorder (EDR)": string,
    "Forward Collision Warning (FCW)": string,
    "Front Air Bag Locations": string,
    "Fuel Delivery / Fuel Injection Type": string,
    "Fuel Type - Primary": string,
    "Fuel Type - Secondary": string,
    "Fuel-Tank Material": string,
    "Fuel-Tank Type": string,
    "Gross Combination Weight Rating From": string,
    "Gross Combination Weight Rating To": string,
    "Gross Vehicle Weight Rating From": string,
    "Gross Vehicle Weight Rating To": string,
    "Headlamp Light Source": string,
    "Keyless Ignition": string,
    "Knee Air Bag Locations": string,
    "Lane Centering Assistance": string,
    "Lane Departure Warning (LDW)": string,
    "Lane Keeping Assistance (LKA)": string,
    "Make": string,
    "Manufacturer Name": string,
    "Model": string,
    "Model Year": string,
    "Motorcycle Chassis Type": string,
    "Motorcycle Suspension Type": string,
    "Non-Land Use": string,
    "Note": string,
    "Number of Battery Cells per Module": string,
    "Number of Battery Modules per Pack": string,
    "Number of Battery Packs per Vehicle": string,
    "Number of Seat Rows": string,
    "Number of Seats": string,
    "Number of Wheels": string,
    "Other Battery Info": string,
    "Other Bus Info": string,
    "Other Engine Info": string,
    "Other Motorcycle Info": string,
    "Other Restraint System Info": string,
    "Other Trailer Info": string,
    "Parking Assist": string,
    "Pedestrian Automatic Emergency Braking (PAEB)": string,
    "Plant City": string,
    "Plant Company Name": string,
    "Plant Country": string,
    "Plant State": string,
    "Possible Values": string,
    "Pretensioner": string,
    "Rear Automatic Emergency Braking": string,
    "Rear Cross Traffic Alert": string,
    "SAE Automation Level From": string,
    "SAE Automation Level To": string,
    "Seat Belt Type": string,
    "Seat Cushion Air Bag Locations": string,
    "Semiautomatic Headlamp Beam Switching": string,
    "Series": string,
    "Series2": string,
    "Side Air Bag Locations": string,
    "Steering Location": string,
    "Suggested VIN": string,
    "Tire Pressure Monitoring System (TPMS) Type": string,
    "Top Speed (MPH)": string,
    "Track Width (inches)": string,
    "Traction Control": string,
    "Trailer Body Type": string,
    "Trailer Length (feet)": string,
    "Trailer Type Connection": string,
    "Transmission Speeds": string,
    "Transmission Style": string,
    "Trim": string,
    "Trim2": string,
    "Turbo": string,
    "Valve Train Design": string,
    "Vehicle Descriptor": string,
    "Vehicle Type": string,
    "Wheel Base (inches) From": string,
    "Wheel Base (inches) To": string,
    "Wheel Base Type": string,
    "Wheel Size Front (inches)": string,
    "Wheel Size Rear (inches)": string,
    "Wheelie Mitigation": string,
    "Windows": string
}

export const createEmptyCarDetail = (): CarDetailsInterface => {
  return {
    "Active Safety System Note": "",
    "Adaptive Cruise Control (ACC)": "",
    "Adaptive Driving Beam (ADB)": "",
    "Additional Error Text": "",
    "Anti-lock Braking System (ABS)": "",
    "Auto-Reverse System for Windows and Sunroofs": "", 
    "Automatic Crash Notification (ACN) / Advanced Automatic Crash Notification (AACN)": "",
    "Automatic Pedestrian Alerting Sound (for Hybrid and EV only)": "",
    "Axle Configuration": "",
    "Axles": "",
    "Backup Camera": "",
    "Base Price ($)": "",
    "Battery Current (Amps) From": "",
    "Battery Current (Amps) To": "",
    "Battery Energy (kWh) From": "",
    "Battery Energy (kWh) To": "",
    "Battery Type": "",
    "Battery Voltage (Volts) From": "",
    "Battery Voltage (Volts) To": "",
    "Bed Length (inches)": "",
    "Bed Type": "",
    "Blind Spot Intervention (BSI)": "",
    "Blind Spot Warning (BSW)": "",
    "Body Class": "",
    "Brake System Description": "",
    "Brake System Type": "",
    "Bus Floor Configuration Type": "",
    "Bus Length (feet)": "",
    "Bus Type": "",
    "Cab Type": "",
    "Charger Level": "",
    "Charger Power (kW)": "",
    "Combined Braking System (CBS)": "",
    "Cooling Type": "",
    "Crash Imminent Braking (CIB)": "",
    "Curb Weight (pounds)": "",
    "Curtain Air Bag Locations": "",
    "Custom Motorcycle Type": "",
    "Daytime Running Light (DRL)": "",
    "Destination Market": "",
    "Displacement (CC)": "",
    "Displacement (CI)": "",
    "Displacement (L)": "",
    "Doors": "",
    "Drive Type": "",
    "Dynamic Brake Support (DBS)": "",
    "EV Drive Unit": "",
    "Electrification Level": "",
    "Electronic Stability Control (ESC)": "",
    "Engine Brake (hp) From": "",
    "Engine Brake (hp) To": "",
    "Engine Configuration": "",
    "Engine Manufacturer": "",
    "Engine Model": "",
    "Engine Number of Cylinders": "",
    "Engine Power (kW)": "",
    "Engine Stroke Cycles": "",
    "Entertainment System": "",
    "Error Code": "",
    "Error Text": "",
    "Event Data Recorder (EDR)": "",
    "Forward Collision Warning (FCW)": "",
    "Front Air Bag Locations": "",
    "Fuel Delivery / Fuel Injection Type": "",
    "Fuel Type - Primary": "",
    "Fuel Type - Secondary": "",
    "Fuel-Tank Material": "",
    "Fuel-Tank Type": "",
    "Gross Combination Weight Rating From": "",
    "Gross Combination Weight Rating To": "",
    "Gross Vehicle Weight Rating From": "",
    "Gross Vehicle Weight Rating To": "",
    "Headlamp Light Source": "",
    "Keyless Ignition": "",
    "Knee Air Bag Locations": "",
    "Lane Centering Assistance": "",
    "Lane Departure Warning (LDW)": "",
    "Lane Keeping Assistance (LKA)": "",
    "Make": "",
    "Manufacturer Name": "",
    "Model": "",
    "Model Year": "",
    "Motorcycle Chassis Type": "",
    "Motorcycle Suspension Type": "",
    "Non-Land Use": "",
    "Note": "",
    "Number of Battery Cells per Module": "",
    "Number of Battery Modules per Pack": "",
    "Number of Battery Packs per Vehicle": "",
    "Number of Seat Rows": "",
    "Number of Seats": "",
    "Number of Wheels": "",
    "Other Battery Info": "",
    "Other Bus Info": "",
    "Other Engine Info": "",
    "Other Motorcycle Info": "",
    "Other Restraint System Info": "",
    "Other Trailer Info": "",
    "Parking Assist": "",
    "Pedestrian Automatic Emergency Braking (PAEB)": "",
    "Plant City": "",
    "Plant Company Name": "",
    "Plant Country": "",
    "Plant State": "",
    "Possible Values": "",
    "Pretensioner": "",
    "Rear Automatic Emergency Braking": "",
    "Rear Cross Traffic Alert": "",
    "SAE Automation Level From": "",
    "SAE Automation Level To": "",
    "Seat Belt Type": "",
    "Seat Cushion Air Bag Locations": "",
    "Semiautomatic Headlamp Beam Switching": "",
    "Series": "",
    "Series2": "",
    "Side Air Bag Locations": "",
    "Steering Location": "",
    "Suggested VIN": "",
    "Tire Pressure Monitoring System (TPMS) Type": "",
    "Top Speed (MPH)": "",
    "Track Width (inches)": "",
    "Traction Control": "",
    "Trailer Body Type": "",
    "Trailer Length (feet)": "",
    "Trailer Type Connection": "",
    "Transmission Speeds": "",
    "Transmission Style": "",
    "Trim": "",
    "Trim2": "",
    "Turbo": "",
    "Valve Train Design": "",
    "Vehicle Descriptor": "",
    "Vehicle Type": "",
    "Wheel Base (inches) From": "",
    "Wheel Base (inches) To": "",
    "Wheel Base Type": "",
    "Wheel Size Front (inches)": "",
    "Wheel Size Rear (inches)": "",
    "Wheelie Mitigation": "",
    "Windows": ""
  }
}

function App() {
  const [carDetails, setCarDetails] = useState<CarDetailsInterface | null>(null);

  return (
    <div className="container roboto-google">
      <header className="header flex-item">
        <h1 className="main-title">🔍 VIN Lookup 🚗</h1>
      </header>
      <section className="vin-form-section flex-item">
        <VinForm setCarDetails={setCarDetails} />
      </section>
      {carDetails && (
        <section className="car-details">
          <CarDetails carDetails={carDetails} />
        </section>
      )}
      <Attribution />
    </div>
  )
}

export default App
